server:
  port: 8083

spring:
  application:
    name: customer-service


    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true

  redis:
    host: localhost
    port: 6379
